"""Initial

Revision ID: f475c85445b6
Revises: 
Create Date: 2026-09-30 10:18:22.468710+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f475c85445b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario', sa.String(length=100), nullable=False),
    sa.Column('no_rebalance', sa.JSON(), nullable=False),
    sa.Column('quarterly', sa.JSON(), nullable=False),
    sa.Column('shock_harvester', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_results_scenario'), 'backtest_results', ['scenario'], unique=False)
    op.create_table('model_portfolios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_weights', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('securities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('asset_class', sa.String(length=30), nullable=False),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('circuit_band_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('is_halted', sa.Boolean(), nullable=False),
    sa.Column('is_index', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_securities_symbol'), 'securities', ['symbol'], unique=True)
    op.create_table('shock_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario', sa.String(length=100), nullable=False),
    sa.Column('magnitude', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('sectors', sa.JSON(), nullable=False),
    sa.Column('vol_multiplier', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='fk_users_client_id', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('risk_profile', sa.String(length=30), nullable=False),
    sa.Column('max_volatility', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('max_drawdown', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model_portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_prices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_prices_price_date'), 'daily_prices', ['price_date'], unique=False)
    op.create_index('ix_daily_prices_security_date', 'daily_prices', ['security_id', 'price_date'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('price_ticks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_ticks_security_ts', 'price_ticks', ['security_id', 'ts'], unique=False)
    op.create_table('rebalance_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shock_event_id', sa.Uuid(), nullable=True),
    sa.Column('portfolios_checked', sa.Integer(), nullable=False),
    sa.Column('portfolios_breached', sa.Integer(), nullable=False),
    sa.Column('portfolios_rebalanced', sa.Integer(), nullable=False),
    sa.Column('blocked_trades', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('stage_timings', sa.JSON(), nullable=True),
    sa.Column('tax_saved_inr', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('losses_harvested_inr', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shock_event_id'], ['shock_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('substitutes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('substitute_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.ForeignKeyConstraint(['substitute_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    op.create_table('commentaries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['rebalance_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commentaries_client_id'), 'commentaries', ['client_id'], unique=False)
    op.create_index(op.f('ix_commentaries_run_id'), 'commentaries', ['run_id'], unique=False)
    op.create_table('cooling_off',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('unblock_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cooling_off_client_id'), 'cooling_off', ['client_id'], unique=False)
    op.create_table('guardrail_violations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('rule', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['rebalance_runs.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guardrail_violations_client_id'), 'guardrail_violations', ['client_id'], unique=False)
    op.create_index(op.f('ix_guardrail_violations_run_id'), 'guardrail_violations', ['run_id'], unique=False)
    op.create_table('realized_gains',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('fy', sa.Integer(), nullable=False),
    sa.Column('stcg', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('ltcg', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('st_loss', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('lt_loss', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_realized_gains_client_id'), 'realized_gains', ['client_id'], unique=False)
    op.create_table('tax_lots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('buy_date', sa.Date(), nullable=False),
    sa.Column('buy_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('original_qty', sa.Integer(), nullable=False),
    sa.Column('remaining_qty', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_lots_client_id'), 'tax_lots', ['client_id'], unique=False)
    op.create_index(op.f('ix_tax_lots_is_active'), 'tax_lots', ['is_active'], unique=False)
    op.create_index(op.f('ix_tax_lots_security_id'), 'tax_lots', ['security_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['rebalance_runs.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_client_id'), 'trades', ['client_id'], unique=False)
    op.create_index(op.f('ix_trades_run_id'), 'trades', ['run_id'], unique=False)
    op.create_table('lot_sales',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lot_id', sa.Uuid(), nullable=False),
    sa.Column('trade_id', sa.Uuid(), nullable=False),
    sa.Column('qty_sold', sa.Integer(), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('proceeds', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gain_loss', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('term', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['tax_lots.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lot_sales')
    op.drop_index(op.f('ix_trades_run_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_client_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_tax_lots_security_id'), table_name='tax_lots')
    op.drop_index(op.f('ix_tax_lots_is_active'), table_name='tax_lots')
    op.drop_index(op.f('ix_tax_lots_client_id'), table_name='tax_lots')
    op.drop_table('tax_lots')
    op.drop_index(op.f('ix_realized_gains_client_id'), table_name='realized_gains')
    op.drop_table('realized_gains')
    op.drop_index(op.f('ix_guardrail_violations_run_id'), table_name='guardrail_violations')
    op.drop_index(op.f('ix_guardrail_violations_client_id'), table_name='guardrail_violations')
    op.drop_table('guardrail_violations')
    op.drop_index(op.f('ix_cooling_off_client_id'), table_name='cooling_off')
    op.drop_table('cooling_off')
    op.drop_index(op.f('ix_commentaries_run_id'), table_name='commentaries')
    op.drop_index(op.f('ix_commentaries_client_id'), table_name='commentaries')
    op.drop_table('commentaries')
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_table('substitutes')
    op.drop_table('rebalance_runs')
    op.drop_index('ix_price_ticks_security_ts', table_name='price_ticks')
    op.drop_table('price_ticks')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_daily_prices_security_date', table_name='daily_prices')
    op.drop_index(op.f('ix_daily_prices_price_date'), table_name='daily_prices')
    op.drop_table('daily_prices')
    op.drop_table('clients')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('shock_events')
    op.drop_index(op.f('ix_securities_symbol'), table_name='securities')
    op.drop_table('securities')
    op.drop_table('model_portfolios')
    op.drop_index(op.f('ix_backtest_results_scenario'), table_name='backtest_results')
    op.drop_table('backtest_results')
    # ### end Alembic commands ###
